### ISSUE TITLE
Multiple bibliography files don't work

### ISSUE THREAD

**Issue by joeroe** [andrewheiss/hikmah-academic-quarto#7]
Quarto supports using multiple bibliography files in a single document by giving `bibliography` as YAML array (https://quarto.org/docs/authoring/citations.html#bibliography-files), e.g.:

```yaml
bibliography:
  - references1.bib
  - references2.bib
format: hikmah-pdf
```

However this doesn't work with hikmah-pdf, because Biber looks for the concatenated path, resulting in the following error:

```
generating bibliography
  INFO - This is Biber 2.20
  [...]
  INFO - Looking for bibtex file 'references1.bibreferences2.bib' for section 0
  ERROR - Cannot find 'references1.bibreferences2.bib'!
  INFO - ERRORS: 1

``
